# === Author: PulpyPuppy ===

# READ THE FUCKIN' COMMENTS
# DON'T PUSH CREDS TO PUBLIC

[credentials]
# Your codingbat account email and password
account_email = ""
account_password = ""
# Your LLM API key here
api_key = ""

[system]
# Supported options: [firefox|chrome|safari]
browser = "chrome"
# true = hide browser window, false = show browser window
# Doesn't work for Safari
headless_mode = false

[paths]
# File to store metadata of the problems
metadata_store = "repo_metadata.json"
# File to store AI-generated solutions
solution_buffer = "ai_payloads.json"

[ai_logic]
# Supported options: [groq|gemini]
llm = "groq"
# Used model id. The default one is recommended
# model_id = "gemini-2.0-flash-lite"
model_id = "llama-3.3-70b-versatile"
# Number or retries after failed connection
retries = 3
# Time to wait in second until the next connection retry
retry_time = 30
# Base range for simulated attempts.
# Total attempts = base_value + (complexity * rank_factor).
min_attempts = 1
max_attempts = 3
rank_factor = 2
# Chose exactly one code_style. These ones are just examples. It is highly recommended to come up with your own "style" he-he
code_style = "Modern Java style: heavy use of Stream API, Optional, and functional interfaces. Elegant one-liners where appropriate, method referencing, and clean separation of concerns."
# code_style = "Standard Java conventions: camelCase for variables/methods, PascalCase for classes. Meaningful variable names (e.g., 'sum', 'result', 'maxValue'). Proper indentation (4 spaces) and consistent brace placement."
# code_style = "Competitive programming style: concise code, short variable names (single letters or 3-letter abbreviations), compact logic, minimal whitespace, focus on performance over readability."
# code_style = "Amateur student style: slightly inconsistent indentation, generic variable names (e.g., 'a', 'b', 'thing', 'temp'), redundant checks (if x == true), and lack of advanced Java features (like Streams)."

[delays]
# Delay after login in seconds (the content to be loaded for sure)
login_wait = 5.0
# Base delay on "thinking" in seconds. It will be muultiplied on the problem complexity.
# Pls change this number
base_think_time = 10.0
